# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

source 'https://github.com/CocoaPods/Specs.git'
target 'GoogleMapsExp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoogleMapsExp
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  target 'GoogleMapsExpTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoogleMapsExpUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
